/*
 * APIs to be used by ONDC Network Participant
 * ONDC Network Participant Onboarding APIs
 *
 * OpenAPI spec version: 0.0.5
 * Contact: team@ondc.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.onsubscribe.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * ReqDinit
 */

@Data
public class ReqKeyOnSubsribe {
	@JsonProperty("client_private_key")
	private String clientPrivateKey = null;

	@JsonProperty("protean_public_key")
	private String proteanPublicKey = null;
}
