/*
 * APIs to be used by ONDC Network Participant
 * ONDC Network Participant Onboarding APIs
 *
 * OpenAPI spec version: 0.0.5
 * Contact: team@ondc.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.response;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * ReqDinit
 */

@Data
public class ResponsOldCityEntityMaster extends ResponsOldEntityParentMaster {

	@JsonProperty("city")
	private String city = null;

	public ResponsOldCityEntityMaster(ResponsOldEntityParentMaster obj, String city) {
		this.subscriberId = obj.getSubscriberId();
		this.status = obj.getStatus();
		this.ukId = obj.getUkId();
		this.subscriberUrl = obj.getSubscriberUrl();

		this.city = city;
		// this.callbackUrl = master.getCallbackUrl();
		this.country = obj.getCountry();
		this.domain = obj.getDomain();

		this.validFrom = obj.getValidFrom();
		this.validUntil = obj.getValidUntil();

		this.type = obj.getType();

		this.signingPublicKey = obj.getSigningPublicKey();
		this.encrPublicKey = obj.getEncrPublicKey();
		this.created = obj.getCreated();
		this.updated = obj.getUpdated();
		this.brId = obj.getBrId();

	}

}
