/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.response;

import java.time.OffsetDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.nsdl.beckn.np.utl.CommonUtl;

import lombok.Data;

/**
 * KeyPair
 */
@Data
public class ResponseKeyPair {
	@JsonProperty("signing_public_key")
	private String signingPublicKey = null;

	@JsonProperty("encryption_public_key")
	private String encryptionPublicKey = null;

	@JsonProperty("valid_from")
	private String validFrom = null;

	@JsonProperty("valid_until")
	private String validUntil = null;

	public ResponseKeyPair(String signingPublicKey, String encryptionPublicKey, OffsetDateTime validFrom,
			OffsetDateTime validUntil) {
		this.signingPublicKey = signingPublicKey;
		this.encryptionPublicKey = encryptionPublicKey;
		this.validFrom = CommonUtl.getDateString(validFrom);
		this.validUntil = CommonUtl.getDateString(validUntil);
	}

	public ResponseKeyPair(String signingPublicKey, String encryptionPublicKey, String validFrom,
			String validUntil) {
		this.signingPublicKey = signingPublicKey;
		this.encryptionPublicKey = encryptionPublicKey;
		this.validFrom = validFrom;
		this.validUntil = validUntil;
	}
}
