/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * EntityGst
 */
@Data
public class EntityGst {

	@JsonProperty("legal_entity_name")
	@SerializedName("legal_entity_name")
	private String legalEntityName = null;

	@JsonProperty("business_address")
	@SerializedName("business_address")
	private String businessAddress = null;

	@JsonProperty("city_code")
	@SerializedName("city_code")
	private List<String> cityCode = null;

	@JsonProperty("gst_no")
	@SerializedName("gst_no")
	private String gstNo = null;

}
