/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * EntityPan
 */
@Data
public class EntityPan {

	@JsonProperty("name_as_per_pan")
	@SerializedName("name_as_per_pan")
	private String nameAsPerPan = null;

	@JsonProperty("pan_no")
	@SerializedName("pan_no")
	private String panNo = null;

	@JsonProperty("date_of_incorporation")
	@SerializedName("date_of_incorporation")
	private String dateOfIncorporation = null;

}
