/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * Entity
 */

@Data
public class Entity {

	@JsonProperty("gst")
	@SerializedName("gst")
	private EntityGst gst = null;

	@JsonProperty("pan")
	@SerializedName("pan")
	private EntityPan pan = null;

	@JsonProperty("name_of_authorised_signatory")
	@SerializedName("name_of_authorised_signatory")
	private String nameOfAuthorisedSignatory = null;

	@JsonProperty("address_of_authorised_signatory")
	@SerializedName("address_of_authorised_signatory")
	private String addressOfAuthorisedSignatory = null;

	@JsonProperty("email_id")
	@SerializedName("email_id")
	private String emailId = null;

	@JsonProperty("mobile_no")
	@SerializedName("mobile_no")
	private String mobileNo = null;

	@JsonProperty("subscriber_id")
	@SerializedName("subscriber_id")
	private String subscriberId = null;

	@JsonProperty("key_pair")
	@SerializedName("key_pair")
	private KeyPair keyPair = null;

	@JsonProperty("effective_date_of_registration")
	@SerializedName("effective_date_of_registration")
	private String effectiveDateOfRegistration = null;

	@JsonProperty("country")
	@SerializedName("country")
	String country;
	
	@JsonProperty("callback_url")
	@SerializedName("callback_url")
	String callbackUrl;

	@JsonProperty("unique_key_id")
	@SerializedName("unique_key_id")
	String uniqueKeyId;
}
