/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.Objects;

import lombok.Data;

@Data
public class ErrorResponseACK {
	private Ack ack = new Ack();

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		ErrorResponseACK inlineResponse200Message = (ErrorResponseACK) o;
		return Objects.equals(this.ack, inlineResponse200Message.ack);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.ack);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class InlineResponse200Message {\n");

		sb.append("    ack: ").append(toIndentedString(this.ack)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
