/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * KeyPair
 */
@Data
public class KeyPair {
	@JsonProperty("signing_public_key")
	@SerializedName("signing_public_key")
	private String signingPublicKey = null;

	@JsonProperty("encryption_public_key")
	@SerializedName("encryption_public_key")
	private String encryptionPublicKey = null;

	@JsonProperty("valid_from")
	@SerializedName("valid_from")
	private String validFrom = null;

	@JsonProperty("valid_until")
	@SerializedName("valid_until")
	private String validUntil = null;

	public KeyPair(String signingPublicKey, String encryptionPublicKey, String validFrom, String validUntil) {
		this.signingPublicKey = signingPublicKey;
		this.encryptionPublicKey = encryptionPublicKey;
		this.validFrom = validFrom;
		this.validUntil = validUntil;
	}

	public KeyPair(String signingPublicKey, String encryptionPublicKey) {
		this.signingPublicKey = signingPublicKey;
		this.encryptionPublicKey = encryptionPublicKey;

	}

	public KeyPair() {

	}

}
