/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * NetworkParticipant
 */
@Data
public class NetworkParticipant {

	@JsonProperty("subscriber_url")
	@SerializedName("subscriber_url")
	private String subscriberUrl = null;

	private String domain = null;

//	@JsonProperty("callback_url")
//
//	private String callbackUrl = null;

	private String type = null;
	private boolean msn = false;

	@JsonProperty("city_code")
	@SerializedName("city_code")
	private List<String> cityCode = null;

	@JsonProperty("seller_on_record")
	@SerializedName("seller_on_record")
	private List<SellerOnRecord> sellerOnRecord = null;

	public String getKey(String subscriberId) {
		return subscriberId + ":" + this.getDomain() + ":" + this.getType() + ":" + this.getSubscriberUrl();
	}
}
