/*
 * APIs to be used by ONDC Network Participant
 * ONDC Network Participant Onboarding APIs
 *
 * OpenAPI spec version: 0.0.5
 * Contact: team@ondc.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
public class ReqLookup {

//	@JsonProperty("sender_subscriber_id")
//	private String senderSubscriberId = null;

	@JsonProperty("subscriber_id")
	private String subscriberId = null;

	@JsonProperty("city")
	private String city = null;

	@JsonProperty("country")
	private String country = null;

	@JsonProperty("domain")
	private String domain = null;

	@JsonProperty("type")
	private String type = null;

}
