/*
 * APIs to be used by ONDC Network Participant
 * ONDC Network Participant Onboarding APIs
 *
 * OpenAPI spec version: 0.0.5
 * Contact: team@ondc.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * ReqDini */

@Data
public class ReqOnSubsribe {
	@JsonProperty("subscriber_id")
	@SerializedName("subscriber_id")
	private String subscriberId = null;

	@JsonProperty("challenge")
	private String challenge = null;
}
