/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * SellerOnRecord
 */
@Data
public class SellerOnRecord {
	@JsonProperty("unique_key_id")
	@SerializedName("unique_key_id")
	private String uniqueKeyId = null;

	@JsonProperty("key_pair")
	@SerializedName("key_pair")
	private KeyPair keyPair = null;

	@JsonProperty("city_code")
	@SerializedName("city_code")
	private List<String> cityCode = null;

	
	public String getKey(String subscriberId) {
		return subscriberId+":"+this.getUniqueKeyId();
	}
	 
}
