/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

/**
 * SubscribeBody
 */

@Data
public class SubscribeBody {
	private SubscribeContext context = new SubscribeContext();

	private SubscribeMessage message = new SubscribeMessage();
	boolean edit;
	@JsonIgnore()
	Map<String, String> msgError = new HashMap();
	
	@JsonIgnore()
	String panStatus;
	@JsonIgnore()
	String panStatusError;
	@JsonIgnore()
	String gstStatus;
	@JsonIgnore()
	String gstStatusError;

}
