/*
 * ONDC Registry
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nsdl.beckn.np.model.request;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import lombok.Data;

/**
 * SubscribeMessage
 */

@Data
public class SubscribeMessage {
	private Entity entity = new Entity();

	@JsonProperty("network_participant")
	@SerializedName("network_participant")
	private List<NetworkParticipant> networkParticipant = null;

	private String timestamp = null;

	@JsonProperty("request_id")
	@SerializedName("request_id")
	private String reqId = null;

}
