name: gcp build & deploy np-onboarding

#on:
#  push:
#   branches: [ actions_gcp ]

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: asia-south1-docker.pkg.dev
  INSTANCE: 2
  SERVICE_NAME: onboarding/demo
  PROJECT_ID: grafana-monitoring-demo # TODO: update Google Cloud project id
  #REGION: asia-south1 # TODO: update Cloud Run service region
  #PORT: 9002

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Image Name
      id: set-image-name
      run: |
          echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/i${{ env.INSTANCE }}-${{ env.SERVICE_NAME }}:$(git rev-parse --short HEAD)" >>${GITHUB_ENV}
          echo "::set-output name=imagename::${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/i${{ env.INSTANCE }}-${{ env.SERVICE_NAME }}:$(git rev-parse --short HEAD)"
    
    - name: Build with Maven
      run: |
          pwd && ls
          whoami
          cd beckn-np-onboarding
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ondc-onboard:v0.0
          
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: grafana-monitoring-demo
        
    - name: Configure Docker to use Artifact Registry
      run: |
        echo "yes" | gcloud auth configure-docker asia-south1-docker.pkg.dev
        
    - name: Push Docker image
      run: |
          docker images
          docker tag fossgen/ondc-beckn-np-onboarding:2.4.0 ${{ env.IMAGE_NAME }}
          docker images
          docker push ${{ env.IMAGE_NAME }}
          docker images
