name: gcp build & deploy np-onboarding

#on:
#  push:
#   branches: [ actions_gcp ]

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build with Maven
      run: |
          pwd && ls
          whoami
          cd beckn-np-onboarding
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ondc-onboard:v0.0
          docker tag fossgen/ondc-beckn-np-onboarding:2.4.0 asia-south1-docker.pkg.dev/grafana-monitoring-demo/i2-np-onboarding:$SHORT_SHA
          docker push asia-south1-docker.pkg.dev/grafana-monitoring-demo/i2-np-onboarding:$SHORT_SHA
